//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_khachhang> tb_khachhang { get; set; }
        public virtual DbSet<tb_sanpham> tb_sanpham { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
        public virtual DbSet<tb_func> tb_func { get; set; }
        public virtual DbSet<tb_congty> tb_congty { get; set; }
        public virtual DbSet<tb_loaiphong> tb_loaiphong { get; set; }
        public virtual DbSet<tb_phong> tb_phong { get; set; }
        public virtual DbSet<tb_phong_thietbi> tb_phong_thietbi { get; set; }
        public virtual DbSet<tb_tang> tb_tang { get; set; }
        public virtual DbSet<tb_thietbi> tb_thietbi { get; set; }
        public virtual DbSet<tb_donvi> tb_donvi { get; set; }
        public virtual DbSet<tb_param> tb_param { get; set; }
        public virtual DbSet<tb_datphong> tb_datphong { get; set; }
        public virtual DbSet<tb_datphong_chitiet> tb_datphong_chitiet { get; set; }
        public virtual DbSet<tb_datphong_sanpham> tb_datphong_sanpham { get; set; }
    }
}
