//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_datphong_sanpham
    {
        public int IDDPSP { get; set; }
        public int IDDP { get; set; }
        public int IDDPCT { get; set; }
        public Nullable<int> IDPHONG { get; set; }
        public Nullable<int> IDSP { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    
        public virtual tb_datphong tb_datphong { get; set; }
        public virtual tb_datphong_chitiet tb_datphong_chitiet { get; set; }
        public virtual tb_phong tb_phong { get; set; }
        public virtual tb_sanpham tb_sanpham { get; set; }
    }
}
