//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_datphong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_datphong()
        {
            this.tb_datphong_chitiet = new HashSet<tb_datphong_chitiet>();
            this.tb_datphong_sanpham = new HashSet<tb_datphong_sanpham>();
        }
    
        public int ID { get; set; }
        public int IDKH { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public Nullable<double> SOTIEN { get; set; }
        public Nullable<int> SONGUOIO { get; set; }
        public int IDUSER { get; set; }
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> DISABLED { get; set; }
        public Nullable<bool> THEODOAN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_datphong_chitiet> tb_datphong_chitiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_datphong_sanpham> tb_datphong_sanpham { get; set; }
        public virtual tb_khachhang tb_khachhang { get; set; }
        public virtual tb_param tb_param { get; set; }
    }
}
