//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_phong()
        {
            this.tb_phong_thietbi = new HashSet<tb_phong_thietbi>();
        }
    
        public int IDPHONG { get; set; }
        public string TENPHONG { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public int IDTANG { get; set; }
        public int IDLOAIPHONG { get; set; }
        public byte[] IMAGE { get; set; }
    
        public virtual tb_loaiphong tb_loaiphong { get; set; }
        public virtual tb_tang tb_tang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_phong_thietbi> tb_phong_thietbi { get; set; }
    }
}
